baseball_stats_definitions = {
    "PlayerId": "Unique identifier for each player.",
    "MLBAMID": "Major League Baseball Advanced Media ID, a unique identifier used by MLB.",
    "Name": "Player's name.",
    "NameASCII": "ASCII representation of the player's name.",
    "Throws": "The hand the player uses to throw (left/right).",
    "Season": "The year or season of the play.",
    "Age": "Player's age.",
    "Team": "The team the player belongs to.",
    "Role": "Position or role of the player in the team.",
    "G": "Number of games in which the player appeared.",
    "GS": "Number of games the player started.",
    "IP": "Total innings a pitcher has thrown.",
    "TBF": "The number of batters a pitcher has faced.",
    "W": "Number of games where the pitcher was pitching while his team took the lead and subsequently won.",
    "L": "Number of games the pitcher lost.",
    "CG": "Games where the pitcher was the only pitcher for his team.",
    "ShO": "Complete games with no runs allowed.",
    "SV": "When a pitcher finishes a game for the winning team under certain conditions.",
    "BS": "Opportunities where the pitcher fails to make a save.",
    "HLD": "When a relief pitcher enters in a save situation, records at least one out, and leaves without his team relinquishing the lead.",
    "SD": "Combination of saves and holds.",
    "MD": "Times the pitcher is removed from the mound.",
    "Pulls": "Times the manager replaces the pitcher.",
    "ERA": "Average number of earned runs a pitcher allows over nine innings.",
    "R": "Total runs allowed.",
    "ER": "Runs for which the pitcher is held accountable.",
    "H": "Total hits allowed.",
    "HR": "Total home runs allowed.",
    "SO": "Total batters struck out.",
    "BB": "Total walks allowed.",
    "IBB": "Walks given intentionally.",
    "HBP": "Batters hit by a pitch.",
    "WP": "Pitches that are too high, low, or wide to be fielded by the catcher, allowing runners to advance.",
    "BK": "Illegal motions by the pitcher that may deceive a baserunner.",
    "Events": "Specific actions that occur during the player's appearance.",
    "GB": "Number of ground balls induced.",
    "LD": "Number of line drives hit off the pitcher.",
    "FB": "Number of fly balls hit off the pitcher.",
    "IFFB": "Fly balls that are caught by an infielder.",
    "BU": "Instances of bunting.",
    "IFH": "Hits that do not leave the infield.",
    "BUH": "Successful bunts that result in a hit.",
    "Balls": "Total number of pitches judged as balls (outside the strike zone and not swung at).",
    "Strikes": "Total number of pitches judged as strikes.",
    "Pitches": "Total number of pitches thrown.",
    "RS": "Runs Scored by the pitcher's team while he was the pitcher of record.",
    "RS_per_9": "Average number of runs scored by the pitcher's team per nine innings.",
    "K_pct": "Percentage of strikeouts per batters faced.",
    "BB_pct": "Percentage of walks per batters faced.",
    "K_minus_BB_pct": "Percentage difference between strikeouts and walks.",
    "K_per_9": "Average number of strikeouts per nine innings pitched.",
    "BB_per_9": "Average number of walks per nine innings pitched.",
    "K_to_BB": "Ratio of strikeouts to walks.",
    "H_per_9": "Average number of hits allowed per nine innings pitched.",
    "HR_per_9": "Average number of home runs allowed per nine innings pitched.",
    "AVG": "Batting average against the pitcher.",
    "WHIP": "Walks plus hits per inning pitched.",
    "BABIP": "Batting average on balls in play.",
    "LOB_pct": "Percentage of runners left on base.",
    "GB_pct": "Percentage of ground balls induced.",
    "LD_pct": "Percentage of line drives allowed.",
    "FB_pct": "Percentage of fly balls allowed.",
    "IFFB_pct": "Percentage of infield fly balls induced.",
    "GB_to_FB": "Ratio of ground balls to fly balls.",
    "HR_to_FB": "Ratio of home runs to fly balls.",
    "IFH_pct": "Percentage of infield hits allowed.",
    "BUH_pct": "Percentage of bunt hits allowed.",
    "FIP": "Fielding Independent Pitching, an ERA estimator based on strikeouts, walks, and home runs allowed.",
    "xFIP": "Expected Fielding Independent Pitching, an estimation of a pitcher's ERA based on strikeouts, walks, and a normalized home run rate.",
    "SIERA": "Skill-Interactive Earned Run Average, an advanced statistic that estimates a pitcher's ERA through batted ball outcomes, strikeouts, and walks.",
    "tERA": "True Earned Run Average, an ERA estimator accounting for the type of batted balls allowed.",
    "kwERA": "Strikeout-to-walk ERA, an ERA estimator based on strikeouts and walks.",
    "E_minus_F": "Difference between the pitcher's ERA and FIP.",
    "RAR": "Runs Above Replacement, the number of runs a player is better than a replacement-level player.",
    "WAR": "Wins Above Replacement, an estimation of the number of wins a player contributes to their team above what a replacement player would contribute.",
    "Dollars": "Estimated market value of the player's contributions.",
    "WPA": "Win Probability Added, the change in win expectancy from one event to the next attributed to the player.",
    "RE24": "Run Expectancy based on the 24 base/out states, the number of runs a player contributes excluding context like inning and score.",
    "REW": "Run Expectancy Wins, the number of wins a player is worth based on run expectancy.",
    "pLI": "Average leverage index when the player bats or pitches; a measure of pressure in those situations.",
    "inLI": "Average leverage index when the player enters the game.",
    "gmLI": "Average leverage index for all game events.",
    "exLI": "Average leverage index when the player exits the game.",
    "WPA_to_LI": "The difference between a player's WPA and what it would be with average leverage.",
    "Clutch": "How much better or worse a player does in high leverage situations than they would have done in a context-neutral environment.",
    "OSwing_pct": "Percentage of pitches a batter swings at outside the strike zone.",
    "ZSwing_pct": "Percentage of pitches a batter swings at inside the strike zone.",
    "Swing_pct": "Overall percentage of pitches a batter swings at.",
    "OContact_pct": "Percentage of times a batter makes contact with pitches swung at outside the strike zone.",
    "ZContact_pct": "Percentage of times a batter makes contact with pitches swung at inside the strike zone.",
    "Contact_pct": "Overall percentage of contact made when swinging at pitches.",
    "Zone_pct": "Percentage of pitches thrown in the strike zone.",
    "FStrike_pct": "Percentage of plate appearances that start with a strike.",
    "SwStr_pct": "Percentage of total pitches that result in a swinging strike.",
    "CStr_pct": "Percentage of total pitches that result in a called strike.",
    "CSW_pct": "Called plus swinging strike percentage.",
    "ERA_minus": "ERA scaled to league average, where 100 is average and lower is better.",
    "FIP_minus": "FIP scaled to league average, where 100 is average and lower is better.",
    "xFIP_minus": "xFIP scaled to league average, where 100 is average and lower is better.",
    "Pace": "Average time between pitches for a pitcher.",
    "RA9_WAR": "Wins above replacement based on runs allowed per nine innings.",
    "BIP_Wins": "Wins above replacement based on batted balls in play.",
    "LOB_Wins": "Wins above replacement based on runners left on base.",
    "FDP_Wins": "Wins above replacement based on fielding dependent pitching.",
    "Pull_pct": "Percentage of batted balls hit to the pull side.",
    "Cent_pct": "Percentage of batted balls hit to center field.",
    "Oppo_pct": "Percentage of batted balls hit to the opposite field.",
    "Soft_pct": "Percentage of softly hit batted balls.",
    "Med_pct": "Percentage of medium hit batted balls.",
    "Hard_pct": "Percentage of hard-hit batted balls.",
    "TTO_pct": "Three true outcomes (home run, walk, strikeout) percentage.",
    "FRM": "Framing runs above average.",
    "K_pct_plus": "Strikeout percentage above league average.",
    "BB_pct_plus": "Walk percentage above league average.",
    "K_per_9_plus": "Strikeouts per nine innings above league average.",
    "BB_per_9_plus": "Walks per nine innings above league average.",
    "K_to_BB_plus": "Strikeout-to-walk ratio above league average.",
    "H_per_9_plus": "Hits per nine innings above league average.",
    "HR_per_9_plus": "Home runs per nine innings above league average.",
    "AVG_plus": "Batting average against above league average.",
    "WHIP_plus": "Walks and hits per inning pitched above league average.",
    "BABIP_plus": "Batting average on balls in play above league average.",
    "LOB_pct_plus": "Left on base percentage above league average.",
    "GB_pct_plus": "Ground ball percentage above league average.",
    "LD_pct_plus": "Line drive percentage above league average.",
    "FB_pct_plus": "Fly ball percentage above league average.",
    "HR_to_FB_pct_plus": "Home run to fly ball percentage above league average.",
    "Pull_pct_plus": "Pull percentage above league average.",
    "Cent_pct_plus": "Center percentage above league average.",
    "Oppo_pct_plus": "Opposite field percentage above league average.",
    "Med_pct_plus": "Medium hit percentage above league average.",
    "Hard_pct_plus": "Hard hit percentage above league average.",
    "EV": "Average exit velocity of batted balls.",
    "LA": "Average launch angle of batted balls.",
    "Barrels": "Batted ball events that have a combination of exit velocity and launch angle that typically produce a minimum .500 batting average and 1.500 slugging percentage.",
    "Barrel_pct": "Percentage of batted balls that are barrels.",
    "maxEV": "Maximum exit velocity of a batted ball.",
    "HardHit": "Batted balls with an exit velocity of 95 mph or more.",
    "HardHit_pct": "Percentage of batted balls that are hard-hit.",
    "FA_pct": "Percentage of fastballs thrown.",
    "FAv": "Average velocity of fastballs thrown.",
    "SL_pct": "Percentage of sliders thrown.",
    "SLv": "Average velocity of sliders thrown.",
    "CT_pct": "Percentage of cutters thrown.",
    "CTv": "Average velocity of cutters thrown.",
    "CB_pct": "Percentage of curveballs thrown.",
    "CBv": "Average velocity of curveballs thrown.",
    "CH_pct": "Percentage of changeups thrown.",
    "CHv": "Average velocity of changeups thrown.",
    "SF_pct": "Percentage of split-finger fastballs thrown.",
    "SFv": "Average velocity of split-finger fastballs thrown.",
    "KN_pct": "Percentage of knuckleballs thrown.",
    "KNv": "Average velocity of knuckleballs thrown.",
    "XX_pct": "Percentage of unknown pitch type thrown.",
    "PO_pct": "Percentage of pitchouts thrown.",
    "wFB": "Weighted fastball runs above average.",
    "wSL": "Weighted slider runs above average.",
    "wCT": "Weighted cutter runs above average.",
    "wCB": "Weighted curveball runs above average.",
    "wCH": "Weighted changeup runs above average.",
    "wSF": "Weighted split-finger fastball runs above average.",
    "wKN": "Weighted knuckleball runs above average.",
    "wFB_per_c": "Weighted fastball runs above average per 100 pitches.",
    "wSL_per_c": "Weighted slider runs above average per 100 pitches.",
    "wCT_per_c": "Weighted cutter runs above average per 100 pitches.",
    "wCB_per_c": "Weighted curveball runs above average per 100 pitches.",
    "wCH_per_c": "Weighted changeup runs above average per 100 pitches.",
    "wSF_per_c": "Weighted split-finger fastball runs above average per 100 pitches.",
    "wKN_per_c": "Weighted knuckleball runs above average per 100 pitches.",
    "FA_pct_sc": "Percentage of four-seam fastballs thrown when considering secondary classification.",
    "FC_pct_sc": "Percentage of cutters thrown when considering secondary classification.",
    "FS_pct_sc": "Percentage of sinkers thrown when considering secondary classification.",
    "FO_pct_sc": "Percentage of forkballs thrown when considering secondary classification.",
    "SI_pct_sc": "Percentage of sinkers thrown when considering secondary classification.",
    "SL_pct_sc": "Percentage of sliders thrown when considering secondary classification.",
    "CU_pct_sc": "Percentage of curveballs thrown when considering secondary classification.",
    "KC_pct_sc": "Percentage of knuckle curves thrown when considering secondary classification.",
    "EP_pct_sc": "Percentage of eephus pitches thrown when considering secondary classification.",
    "CH_pct_sc": "Percentage of changeups thrown when considering secondary classification.",
    "SC_pct_sc": "Percentage of screwballs thrown when considering secondary classification.",
    "KN_pct_sc": "Percentage of knuckleballs thrown when considering secondary classification.",
    "UN_pct_sc": "Percentage of unknown pitch type thrown when considering secondary classification.",
    "vFA_sc": "Velocity of four-seam fastballs when considering secondary classification.",
    "vFC_sc": "Velocity of cutters when considering secondary classification.",
    "vFS_sc": "Velocity of sinkers when considering secondary classification.",
    "vFO_sc": "Velocity of forkballs when considering secondary classification.",
    "vSI_sc": "Velocity of sinkers when considering secondary classification.",
    "vSL_sc": "Velocity of sliders when considering secondary classification.",
    "vCU_sc": "Velocity of curveballs when considering secondary classification.",
    "vKC_sc": "Velocity of knuckle curves when considering secondary classification.",
    "vEP_sc": "Velocity of eephus pitches when considering secondary classification.",
    "vCH_sc": "Velocity of changeups when considering secondary classification.",
    "vSC_sc": "Velocity of screwballs when considering secondary classification.",
    "vKN_sc": "Velocity of knuckleballs when considering secondary classification.",
    "FA_X_sc": "Horizontal movement of four-seam fastballs when considering secondary classification.",
    "FC_X_sc": "Horizontal movement of cutters when considering secondary classification.",
    "FS_X_sc": "Horizontal movement of sinkers when considering secondary classification.",
    "FO_X_sc": "Horizontal movement of forkballs when considering secondary classification.",
    "SI_X_sc": "Horizontal movement of sinkers when considering secondary classification.",
    "SL_X_sc": "Horizontal movement of sliders when considering secondary classification.",
    "CU_X_sc": "Horizontal movement of curveballs when considering secondary classification.",
    "KC_X_sc": "Horizontal movement of knuckle curves when considering secondary classification.",
    "EP_X_sc": "Horizontal movement of eephus pitches when considering secondary classification.",
    "CH_X_sc": "Horizontal movement of changeups when considering secondary classification.",
    "SC_X_sc": "Horizontal movement of screwballs when considering secondary classification.",
    "KN_X_sc": "Horizontal movement of knuckleballs when considering secondary classification.",
    "FA_Z_sc": "Vertical movement of four-seam fastballs when considering secondary classification.",
     "FC_Z_sc": "Vertical movement of cutters when considering secondary classification.",
    "FS_Z_sc": "Vertical movement of sinkers when considering secondary classification.",
    "FO_Z_sc": "Vertical movement of forkballs when considering secondary classification.",
    "SI_Z_sc": "Vertical movement of sinkers when considering secondary classification.",
    "SL_Z_sc": "Vertical movement of sliders when considering secondary classification.",
    "CU_Z_sc": "Vertical movement of curveballs when considering secondary classification.",
    "KC_Z_sc": "Vertical movement of knuckle curves when considering secondary classification.",
    "EP_Z_sc": "Vertical movement of eephus pitches when considering secondary classification.",
    "CH_Z_sc": "Vertical movement of changeups when considering secondary classification.",
    "SC_Z_sc": "Vertical movement of screwballs when considering secondary classification.",
    "KN_Z_sc": "Vertical movement of knuckleballs when considering secondary classification.",
    "wFA_sc": "Weighted four-seam fastball runs above average when considering secondary classification.",
    "wFC_sc": "Weighted cutter runs above average when considering secondary classification.",
    "wFS_sc": "Weighted sinker runs above average when considering secondary classification.",
    "wFO_sc": "Weighted forkball runs above average when considering secondary classification.",
    "wSI_sc": "Weighted sinker runs above average when considering secondary classification.",
    "wSL_sc": "Weighted slider runs above average when considering secondary classification.",
    "wCU_sc": "Weighted curveball runs above average when considering secondary classification.",
    "wKC_sc": "Weighted knuckle curve runs above average when considering secondary classification.",
    "wEP_sc": "Weighted eephus pitch runs above average when considering secondary classification.",
    "wCH_sc": "Weighted changeup runs above average when considering secondary classification.",
    "wSC_sc": "Weighted screwball runs above average when considering secondary classification.",
    "wKN_sc": "Weighted knuckleball runs above average when considering secondary classification.",
    "wFA_per_c_sc": "Weighted four-seam fastball runs above average per 100 pitches when considering secondary classification.",
    "wFC_per_c_sc": "Weighted cutter runs above average per 100 pitches when considering secondary classification.",
    "wFS_per_c_sc": "Weighted sinker runs above average per 100 pitches when considering secondary classification.",
    "wFO_per_c_sc": "Weighted forkball runs above average per 100 pitches when considering secondary classification.",
    "wSI_per_c_sc": "Weighted sinker runs above average per 100 pitches when considering secondary classification.",
    "wSL_per_c_sc": "Weighted slider runs above average per 100 pitches when considering secondary classification.",
    "wCU_per_c_sc": "Weighted curveball runs above average per 100 pitches when considering secondary classification.",
    "wKC_per_c_sc": "Weighted knuckle curve runs above average per 100 pitches when considering secondary classification.",
    "wEP_per_c_sc": "Weighted eephus pitch runs above average per 100 pitches when considering secondary classification.",
    "wCH_per_c_sc": "Weighted changeup runs above average per 100 pitches when considering secondary classification.",
    "wSC_per_c_sc": "Weighted screwball runs above average per 100 pitches when considering secondary classification.",
    "wKN_per_c_sc": "Weighted knuckleball runs above average per 100 pitches when considering secondary classification.",
    "OSwing_pct_sc": "Percentage of pitches a batter swings at outside the strike zone when considering secondary classification.",
    "ZSwing_pct_sc": "Percentage of pitches a batter swings at inside the strike zone when considering secondary classification.",
    "Swing_pct_sc": "Overall percentage of pitches a batter swings at when considering secondary classification.",
    "OContact_pct_sc": "Percentage of times a batter makes contact with pitches swung at outside the strike zone when considering secondary classification.",
    "ZContact_pct_sc": "Percentage of times a batter makes contact with pitches swung at inside the strike zone when considering secondary classification.",
    "Contact_pct_sc": "Overall percentage of contact made when swinging at pitches when considering secondary classification.",
    "Zone_pct_sc": "Percentage of pitches thrown in the strike zone when considering secondary classification.",
     "botERA": "ERA as evaluated by PitchingBot, reflecting the pitcher's effectiveness.",
    "botOvr_CH": "Overall grade for changeups as evaluated by PitchingBot.",
    "botStf_CH": "Grade for the 'stuff' quality of changeups as evaluated by PitchingBot.",
    "botCmd_CH": "Grade for the command of changeups as evaluated by PitchingBot.",
    "botOvr_CU": "Overall grade for curveballs as evaluated by PitchingBot.",
    "botStf_CU": "Grade for the 'stuff' quality of curveballs as evaluated by PitchingBot.",
    "botCmd_CU": "Grade for the command of curveballs as evaluated by PitchingBot.",
    "botOvr_FA": "Overall grade for fastballs as evaluated by PitchingBot.",
    "botStf_FA": "Grade for the 'stuff' quality of fastballs as evaluated by PitchingBot.",
    "botCmd_FA": "Grade for the command of fastballs as evaluated by PitchingBot.",
    "botOvr_SI": "Overall grade for sinkers as evaluated by PitchingBot.",
    "botStf_SI": "Grade for the 'stuff' quality of sinkers as evaluated by PitchingBot.",
    "botCmd_SI": "Grade for the command of sinkers as evaluated by PitchingBot.",
    "botOvr_SL": "Overall grade for sliders as evaluated by PitchingBot.",
    "botStf_SL": "Grade for the 'stuff' quality of sliders as evaluated by PitchingBot.",
    "botCmd_SL": "Grade for the command of sliders as evaluated by PitchingBot.",
    "botOvr_KC": "Overall grade for knuckle-curves as evaluated by PitchingBot.",
    "botStf_KC": "Grade for the 'stuff' quality of knuckle-curves as evaluated by PitchingBot.",
    "botCmd_KC": "Grade for the command of knuckle-curves as evaluated by PitchingBot.",
    "botOvr_FC": "Overall grade for cutters as evaluated by PitchingBot.",
    "botStf_FC": "Grade for the 'stuff' quality of cutters as evaluated by PitchingBot.",
    "botCmd_FC": "Grade for the command of cutters as evaluated by PitchingBot.",
    "botOvr_FS": "Overall grade for split-fingers as evaluated by PitchingBot.",
    "botStf_FS": "Grade for the 'stuff' quality of split-fingers as evaluated by PitchingBot.",
    "botCmd_FS": "Grade for the command of split-fingers as evaluated by PitchingBot.",
    "botOvr": "Overall pitching grade as evaluated by PitchingBot.",
    "botStf": "Overall 'stuff' grade as evaluated by PitchingBot.",
    "botCmd": "Overall command grade as evaluated by PitchingBot.",
    "botxRV100": "Expected run value per 100 pitches as calculated by PitchingBot.",
    "Stf_plus_CH": "Enhanced 'stuff' grade for changeups by Pitching+.",
    "Loc_plus_CH": "Enhanced location grade for changeups by Pitching+.",
    "Pit_plus_CH": "Enhanced overall pitching grade for changeups by Pitching+.",
    "Stf_plus_CU": "Enhanced 'stuff' grade for curveballs by Pitching+.",
    "Loc_plus_CU": "Enhanced location grade for curveballs by Pitching+.",
    "Pit_plus_CU": "Enhanced overall pitching grade for curveballs by Pitching+.",
    "Stf_plus_FA": "Enhanced 'stuff' grade for fastballs by Pitching+.",
    "Loc_plus_FA": "Enhanced location grade for fastballs by Pitching+.",
    "Pit_plus_FA": "Enhanced overall pitching grade for fastballs by Pitching+.",
    "Stf_plus_SI": "Enhanced 'stuff' grade for sinkers by Pitching+.",
    "Loc_plus_SI": "Enhanced location grade for sinkers by Pitching+.",
    "Pit_plus_SI": "Enhanced overall pitching grade for sinkers by Pitching+.",
    "Stf_plus_SL": "Enhanced 'stuff' grade for sliders by Pitching+.",
    "Loc_plus_SL": "Enhanced location grade for sliders by Pitching+.",
    "Pit_plus_SL": "Enhanced overall pitching grade for sliders by Pitching+.",
    "Stf_plus_KC": "Enhanced 'stuff' grade for knuckle-curves by Pitching+.",
    "Loc_plus_KC": "Enhanced location grade for knuckle-curves by Pitching+.",
    "Pit_plus_KC": "Enhanced overall pitching grade for knuckle-curves by Pitching+.",
    "Stf_plus_FC": "Enhanced 'stuff' grade for cutters by Pitching+.",
    "Loc_plus_FC": "Enhanced location grade for cutters by Pitching+.",
    "Pit_plus_FC": "Enhanced overall pitching grade for cutters by Pitching+.",
    "Stf_plus_FS": "Enhanced 'stuff' grade for split-fingers by Pitching+.",
    "Loc_plus_FS": "Enhanced location grade for split-fingers by Pitching+.",
    "Pit_plus_FS": "Enhanced overall pitching grade for split-fingers by Pitching+.",
    "Stf_plus_FO": "Enhanced 'stuff' grade for forkballs by Pitching+.",
    "Loc_plus_FO": "Enhanced location grade for forkballs by Pitching+.",
    "Pit_plus_FO": "Enhanced overall pitching grade for forkballs by Pitching+.",
    "Stuff_plus": "Overall 'stuff' grade enhanced by Pitching+.",
    "Location_plus": "Overall location grade enhanced by Pitching+.",
    "Pitching_plus": "Overall pitching grade enhanced by Pitching+."
}
# Definitions for the baseball stats